# Generated by Django 2.2.5 on 2022-07-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
