# Generated by Django 2.2.5 on 2022-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQA', '0002_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='work',
            field=models.CharField(default='', max_length=100),
        ),
    ]
