# Generated by Django 2.2.5 on 2022-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQA', '0003_student_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrecord',
            name='question_text',
            field=models.CharField(max_length=2000),
        ),
    ]
