# Generated by Django 2.2.5 on 2022-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentQA', '0004_auto_20220727_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='similar_question',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionrecord',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
